import 'package:flutter/material.dart';
import 'package:unicars/give_review_screen.dart';
import 'login_screen.dart';
import 'package:camera/camera.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Μπορεί να το δημιουργήσεις με το FlutterFire CLI
import 'edit_profile_screen.dart';
import 'show_prof1_screen.dart';
import 'choose_driver_screen.dart';
import 'register_screen.dart';
import 'package:geolocator/geolocator.dart';
import 'package:permission_handler/permission_handler.dart';
import 'dart:async';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

Future<void> requestLocationPermission() async {
  var status = await Permission.location.request();
  if (status.isGranted) {
    print('Permission granted');
  } else {
    print('Permission denied');
  }
}

void setupFirebaseMessaging() async {
  FirebaseMessaging messaging = FirebaseMessaging.instance;

  // Ζήτα άδεια για ειδοποιήσεις
  NotificationSettings settings = await messaging.requestPermission();

  if (settings.authorizationStatus == AuthorizationStatus.authorized) {
    print('User granted permission');
  }

  // Πάρε το FCM token της συσκευής
  String? token = await messaging.getToken();
  print("FCM Token: $token");

  // Μπορείς να το αποθηκεύσεις στο Firestore:
  // FirebaseFirestore.instance.collection('users').doc(userId).update({'fcmToken': token});
}


List<CameraDescription> cameras = [];

void startUploadingLocation(String userId) {
  Timer.periodic(const Duration(minutes: 1), (_) async {
    try {
  Position position = await Geolocator.getCurrentPosition();
  await FirebaseFirestore.instance.collection('users').doc(userId).update({
    'latitude': position.latitude,
    'longitude': position.longitude,
    'lastUpdated': FieldValue.serverTimestamp(),
  });
} catch (e) {
  print('Error getting location: $e');
}
  });
}

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }
  } catch (e) {
    print('Firebase already initialized: $e');
  }

  try {
    cameras = await availableCameras();
  } on CameraException catch (e) {
    print('Error in fetching the cameras: $e');
  }

  runApp(const Unicars());
}







// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class Unicars extends StatefulWidget {
  const Unicars({super.key});

  @override
  State<Unicars> createState() => _UnicarsState();
}

class _UnicarsState extends State<Unicars> {
  @override
  void initState() {
    super.initState();
    _initLocationUpdates();
  }

  Future<void> _initLocationUpdates() async {
    final currentUser = FirebaseAuth.instance.currentUser;
    if (currentUser != null) {
      final granted = await Permission.location.request();
      if (granted.isGranted) {
        startUploadingLocation(currentUser.uid);
      } else {
        print('Location permission not granted');
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          LoadingScreen(),
        ]),
      ),
    );
  }
}


class LoadingScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: MediaQuery.of(context).size.width,
          height: MediaQuery.of(context).size.height,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: const Color(0xFF072B58)),
          child: Stack(
            children: [
              Positioned(
                left: 46,
                top: 344,
                child: GestureDetector(  // Added GestureDetector
                  onTap: () {
                    Navigator.push(
                      context,
                      MaterialPageRoute(builder: (context) => Login()),
                    );
                  },
                  child: Container(
                    width: 319,
                    height: 319,
                    child: Stack(
                      children: [
                        Positioned(
                          left: 0,
                          top: 0,
                          child: Container(
                            width: 319,
                            height: 319,
                            decoration: ShapeDecoration(
                              image: DecorationImage(
                                image: AssetImage("assets/images/logocar.png"),
                                fit: BoxFit.cover,
                              ),
                              shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(90),
                              ),
                            ),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 122,
                top: 222,
                child: SizedBox(
                  width: 215,
                  height: 45,
                  child: Text(
                    'UniCars',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 40,
                      fontFamily: 'Kiwi Maru',
                      fontWeight: FontWeight.w400,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}